const playersData = [
  {
    rank: 1,
    name: 'ShadowRunner',
    score: 17420,
    progress: 'Alpha',
    status: 'Online',
    lastActive: 'Now playing',
    liveRoom: 'Treasure Vault',
    region: 'Europe',
    doorsCleared: 53,
    totalRuns: 128,
    favoriteWeapon: 'Dark Seal',
    bestRun: 'Level 90',
    notes: 'Leader by score and playtime, always active.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/ShadowRunner.svg',
    knobsEarned: 45230,
    revivesEarned: 15,
    stardustEarned: 120,
    goldEarned: 8900,
    totalWins: 45,
    winsHotel: 25,
    winsMines: 12,
    winsBackdoor: 5,
    winsRooms: 2,
    winsOutdoors: 1,
    achievementsUnlocked: 89,
    modifiersUsed: 67,
    itemsCollected: 234
  },
  {
    rank: 2,
    name: 'DoorHunter',
    score: 16130,
    progress: 'Ghost',
    status: 'Offline',
    lastActive: '10 minutes ago',
    liveRoom: 'Cursed Tower',
    region: 'North America',
    doorsCleared: 48,
    totalRuns: 101,
    favoriteWeapon: 'Phantom Dagger',
    bestRun: 'Level 86',
    notes: 'Consistent runner with strong late-game results.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/DoorHunter.svg',
    knobsEarned: 38900,
    revivesEarned: 12,
    stardustEarned: 95,
    goldEarned: 7200,
    totalWins: 38,
    winsHotel: 20,
    winsMines: 10,
    winsBackdoor: 4,
    winsRooms: 3,
    winsOutdoors: 1,
    achievementsUnlocked: 76,
    modifiersUsed: 54,
    itemsCollected: 198
  },
  {
    rank: 3,
    name: 'NightStalker',
    score: 14950,
    progress: 'Nightmare',
    status: 'Online',
    lastActive: '3 minutes ago',
    liveRoom: 'Dark Labyrinth',
    region: 'Asia',
    doorsCleared: 45,
    totalRuns: 89,
    favoriteWeapon: 'Moon Scythe',
    bestRun: 'Level 84',
    notes: 'Fast climber who can jump in ranking quickly.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/NightStalker.svg',
    knobsEarned: 32100,
    revivesEarned: 10,
    stardustEarned: 78,
    goldEarned: 6500,
    totalWins: 32,
    winsHotel: 18,
    winsMines: 8,
    winsBackdoor: 3,
    winsRooms: 2,
    winsOutdoors: 1,
    achievementsUnlocked: 68,
    modifiersUsed: 45,
    itemsCollected: 176
  },
  {
    rank: 4,
    name: 'BladeMage',
    score: 13890,
    progress: 'Canyon',
    status: 'Offline',
    lastActive: '1 hour ago',
    liveRoom: 'The Ruins',
    region: 'Europe',
    doorsCleared: 41,
    totalRuns: 78,
    favoriteWeapon: 'Flame Staff',
    bestRun: 'Level 80',
    notes: 'Strong team player with deep map knowledge.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/BladeMage.svg',
    knobsEarned: 28900,
    revivesEarned: 8,
    stardustEarned: 65,
    goldEarned: 5800,
    totalWins: 28,
    winsHotel: 16,
    winsMines: 7,
    winsBackdoor: 3,
    winsRooms: 1,
    winsOutdoors: 1,
    achievementsUnlocked: 59,
    modifiersUsed: 38,
    itemsCollected: 154
  },
  {
    rank: 5,
    name: 'LunaPick',
    score: 13100,
    progress: 'Lost Floor',
    status: 'Online',
    lastActive: 'Now online',
    liveRoom: 'Shadow Labyrinth',
    region: 'South America',
    doorsCleared: 39,
    totalRuns: 72,
    favoriteWeapon: 'Moonshot',
    bestRun: 'Level 78',
    notes: 'Explorer who loves rare rooms and risky runs.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/LunaPick.svg',
    knobsEarned: 25600,
    revivesEarned: 7,
    stardustEarned: 52,
    goldEarned: 5100,
    totalWins: 24,
    winsHotel: 14,
    winsMines: 6,
    winsBackdoor: 2,
    winsRooms: 1,
    winsOutdoors: 1,
    achievementsUnlocked: 51,
    modifiersUsed: 32,
    itemsCollected: 132
  },
  {
    rank: 6,
    name: 'AbyssWalker',
    score: 12240,
    progress: 'Night Mode',
    status: 'Offline',
    lastActive: '2 hours ago',
    liveRoom: 'Abyssal Rift',
    region: 'Australia',
    doorsCleared: 36,
    totalRuns: 67,
    favoriteWeapon: 'Blade of Oblivion',
    bestRun: 'Level 76',
    notes: 'Survival specialist for the toughest floors.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/AbyssWalker.svg',
    knobsEarned: 22300,
    revivesEarned: 6,
    stardustEarned: 45,
    goldEarned: 4400,
    totalWins: 20,
    winsHotel: 12,
    winsMines: 5,
    winsBackdoor: 2,
    winsRooms: 1,
    winsOutdoors: 0,
    achievementsUnlocked: 44,
    modifiersUsed: 28,
    itemsCollected: 118
  },
  {
    rank: 7,
    name: 'GhostBlink',
    score: 11300,
    progress: 'Phantom Realm',
    status: 'Online',
    lastActive: 'Now playing',
    liveRoom: 'Ghostly Halls',
    region: 'North America',
    doorsCleared: 33,
    totalRuns: 58,
    favoriteWeapon: 'Spectral Bow',
    bestRun: 'Level 74',
    notes: 'Master of evasion and quick escapes.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/GhostBlink.svg',
    knobsEarned: 19800,
    revivesEarned: 5,
    stardustEarned: 38,
    goldEarned: 3800,
    totalWins: 18,
    winsHotel: 10,
    winsMines: 4,
    winsBackdoor: 2,
    winsRooms: 1,
    winsOutdoors: 1,
    achievementsUnlocked: 38,
    modifiersUsed: 24,
    itemsCollected: 102
  }
];