const playersData = [
  {
    rank: 1,
    name: 'ShadowRunner',
    score: 17420,
    progress: 'Alpha',
    status: 'Online',
    lastActive: 'Now playing',
    liveRoom: 'Treasure Vault',
    region: 'Europe',
    doorsCleared: 53,
    totalRuns: 128,
    favoriteWeapon: 'Dark Seal',
    bestRun: 'Level 90',
    notes: 'Leader by score and playtime, always active.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/ShadowRunner.svg'
  },
  {
    rank: 2,
    name: 'DoorHunter',
    score: 16130,
    progress: 'Ghost',
    status: 'Offline',
    lastActive: '10 minutes ago',
    liveRoom: 'Cursed Tower',
    region: 'North America',
    doorsCleared: 48,
    totalRuns: 101,
    favoriteWeapon: 'Phantom Dagger',
    bestRun: 'Level 86',
    notes: 'Consistent runner with strong late-game results.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/DoorHunter.svg'
  },
  {
    rank: 3,
    name: 'NightStalker',
    score: 14950,
    progress: 'Nightmare',
    status: 'Online',
    lastActive: '3 minutes ago',
    liveRoom: 'Dark Labyrinth',
    region: 'Asia',
    doorsCleared: 45,
    totalRuns: 89,
    favoriteWeapon: 'Moon Scythe',
    bestRun: 'Level 84',
    notes: 'Fast climber who can jump in ranking quickly.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/NightStalker.svg'
  },
  {
    rank: 4,
    name: 'BladeMage',
    score: 13890,
    progress: 'Canyon',
    status: 'Offline',
    lastActive: '1 hour ago',
    liveRoom: 'The Ruins',
    region: 'Europe',
    doorsCleared: 41,
    totalRuns: 78,
    favoriteWeapon: 'Flame Staff',
    bestRun: 'Level 80',
    notes: 'Strong team player with deep map knowledge.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/BladeMage.svg'
  },
  {
    rank: 5,
    name: 'LunaPick',
    score: 13100,
    progress: 'Lost Floor',
    status: 'Online',
    lastActive: 'Now online',
    liveRoom: 'Shadow Labyrinth',
    region: 'South America',
    doorsCleared: 39,
    totalRuns: 72,
    favoriteWeapon: 'Moonshot',
    bestRun: 'Level 78',
    notes: 'Explorer who loves rare rooms and risky runs.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/LunaPick.svg'
  },
  {
    rank: 6,
    name: 'AbyssWalker',
    score: 12240,
    progress: 'Night Mode',
    status: 'Offline',
    lastActive: '2 hours ago',
    liveRoom: 'Abyssal Rift',
    region: 'Australia',
    doorsCleared: 36,
    totalRuns: 67,
    favoriteWeapon: 'Blade of Oblivion',
    bestRun: 'Level 76',
    notes: 'Survival specialist for the toughest floors.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/AbyssWalker.svg'
  },
  {
    rank: 7,
    name: 'GhostBlink',
    score: 11450,
    progress: 'Lost Floor',
    status: 'Online',
    lastActive: 'Online now',
    liveRoom: 'Shadow City',
    region: 'Europe',
    doorsCleared: 35,
    totalRuns: 64,
    favoriteWeapon: 'Shadow Harp',
    bestRun: 'Level 75',
    notes: 'Adapts quickly to new mechanics and maps.',
    avatarUrl: 'https://avatars.dicebear.com/api/avataaars/GhostBlink.svg'
  }
];
